# Application
export ENVIRONMENT='development'

# Authentication
export ENCRYPTION_KEY='1234567890'
export API_COOKIE_SECRET='1234567890'

# AWS
export SALESSPARROW_ACCESS_KEY_ID=''
export SALESSPARROW_SECRET_ACCESS_KEY=''
export SALESSPARROW_REGION=''
export SALESSPARROW_CACHE_CLUSTER_ID=''
export KMS_KEY_ID=''

# Dynamo DB
export DYNAMO_DB_URL=''

# Salesforce
export SALESFORCE_AUTH_URL=''
export SALESFORCE_CLIENT_ID=''
export SALESFORCE_CLIENT_SECRET=''

# Local Cache
export LOCAL_CACHE_HOST='memcached'
export LOCAL_CACHE_PORT='11211'