Table salesforce_organizations {
  id bigint [pk, increment]
  external_organization_id varchar 
  status salesforce_organizations_status
  created_at timestamp
  updated_at timestamp
  indexes {
    (external_organization_id) [unique]
  }
}

Table salesforce_oauth_tokens {
  id bigint [pk, increment]
  salesforce_user_id varchar
  identity_url varchar 
  access_token varchar
  refresh_token varchar
  signature varchar
  id_token varchar
  instance_url varchar
  status salesforce_oauth_tokens_status
  issued_at timestamp
  created_at timestamp
  updated_at timestamp
  indexes {
    (salesforce_user_id) [unique]
  }
}

Table salesforce_users {
  id bigint [pk, increment]
  external_user_id varchar 
  identity_url varchar 
  salesforce_organization_id varchar 
  name varchar
  email varchar 
  user_type varchar
  cookie_token varchar 
  encryption_salt varchar 
  status salesforce_users_status 
  created_at timestamp 
  updated_at timestamp 
  indexes {
    (external_user_id) [unique]
  }
}

Enum salesforce_organizations_status {
active
deleted
}

Enum salesforce_oauth_tokens_status {
active
deleted
}

Enum salesforce_users_status {
active
deleted
}